var searchData=
[
  ['radiusresultset',['RadiusResultSet',['../classcvflann_1_1_radius_result_set.html',1,'cvflann']]],
  ['radiusuniqueresultset',['RadiusUniqueResultSet',['../classcvflann_1_1_radius_unique_result_set.html',1,'cvflann']]],
  ['range',['Range',['../classcv_1_1_range.html',1,'cv']]],
  ['ransacparams',['RansacParams',['../structcv_1_1videostab_1_1_ransac_params.html',1,'cv::videostab']]],
  ['rebind',['rebind',['../classcv_1_1_allocator_1_1rebind.html',1,'cv::Allocator']]],
  ['rect',['Rect',['../struct_slide_over_kit_1_1_rect.html',1,'SlideOverKit']]],
  ['rect_5f',['Rect_',['../classcv_1_1_rect__.html',1,'cv']]],
  ['regionlayer',['RegionLayer',['../classcv_1_1dnn_1_1_region_layer.html',1,'cv::dnn']]],
  ['relu6layer',['ReLU6Layer',['../classcv_1_1dnn_1_1_re_l_u6_layer.html',1,'cv::dnn']]],
  ['relulayer',['ReLULayer',['../classcv_1_1dnn_1_1_re_l_u_layer.html',1,'cv::dnn']]],
  ['reorglayer',['ReorgLayer',['../classcv_1_1dnn_1_1_reorg_layer.html',1,'cv::dnn']]],
  ['reshapelayer',['ReshapeLayer',['../classcv_1_1dnn_1_1_reshape_layer.html',1,'cv::dnn']]],
  ['resizelayer',['ResizeLayer',['../classcv_1_1dnn_1_1_resize_layer.html',1,'cv::dnn']]],
  ['resource',['Resource',['../class_slide_over_kit_1_1_more_sample_1_1_droid_1_1_resource.html',1,'SlideOverKit::MoreSample::Droid']]],
  ['resultset',['ResultSet',['../classcvflann_1_1_result_set.html',1,'cvflann']]],
  ['rg_5fplugins_5fpopup_5fios_5frenderers_5fpopuppagerenderer',['Rg_Plugins_Popup_IOS_Renderers_PopupPageRenderer',['../interface_rg___plugins___popup___i_o_s___renderers___popup_page_renderer.html',1,'']]],
  ['rgpopupplatformrenderer',['RgPopupPlatformRenderer',['../interface_rg_popup_platform_renderer.html',1,'']]],
  ['rgpopupwindow',['RgPopupWindow',['../interface_rg_popup_window.html',1,'']]],
  ['rightsidedetailpage',['RightSideDetailPage',['../class_slide_over_kit_1_1_more_sample_1_1_right_side_detail_page.html',1,'SlideOverKit::MoreSample']]],
  ['rightsidemasterpage',['RightSideMasterPage',['../class_slide_over_kit_1_1_more_sample_1_1_right_side_master_page.html',1,'SlideOverKit::MoreSample']]],
  ['rng',['RNG',['../classcv_1_1_r_n_g.html',1,'cv']]],
  ['rng_5fmt19937',['RNG_MT19937',['../classcv_1_1_r_n_g___m_t19937.html',1,'cv']]],
  ['rnnlayer',['RNNLayer',['../classcv_1_1dnn_1_1_r_n_n_layer.html',1,'cv::dnn']]],
  ['rotatedrect',['RotatedRect',['../classcv_1_1_rotated_rect.html',1,'cv']]],
  ['rotationwarper',['RotationWarper',['../classcv_1_1detail_1_1_rotation_warper.html',1,'cv::detail']]],
  ['rotationwarperbase',['RotationWarperBase',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20compressedrectilinearportraitprojector_20_3e',['RotationWarperBase&lt; CompressedRectilinearPortraitProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20compressedrectilinearprojector_20_3e',['RotationWarperBase&lt; CompressedRectilinearProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20cylindricalportraitprojector_20_3e',['RotationWarperBase&lt; CylindricalPortraitProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20cylindricalprojector_20_3e',['RotationWarperBase&lt; CylindricalProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20fisheyeprojector_20_3e',['RotationWarperBase&lt; FisheyeProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20mercatorprojector_20_3e',['RotationWarperBase&lt; MercatorProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20paniniportraitprojector_20_3e',['RotationWarperBase&lt; PaniniPortraitProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20paniniprojector_20_3e',['RotationWarperBase&lt; PaniniProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20planeportraitprojector_20_3e',['RotationWarperBase&lt; PlanePortraitProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20planeprojector_20_3e',['RotationWarperBase&lt; PlaneProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20sphericalportraitprojector_20_3e',['RotationWarperBase&lt; SphericalPortraitProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20sphericalprojector_20_3e',['RotationWarperBase&lt; SphericalProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20stereographicprojector_20_3e',['RotationWarperBase&lt; StereographicProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20transversemercatorprojector_20_3e',['RotationWarperBase&lt; TransverseMercatorProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]]
];
