var searchData=
[
  ['pacadprovider',['PACAdProvider',['../interface_p_a_c_ad_provider.html',1,'']]],
  ['pacconsentform',['PACConsentForm',['../interface_p_a_c_consent_form.html',1,'']]],
  ['pacconsentinformation',['PACConsentInformation',['../interface_p_a_c_consent_information.html',1,'']]],
  ['paddinglayer',['PaddingLayer',['../classcv_1_1dnn_1_1_padding_layer.html',1,'cv::dnn']]],
  ['pageimpinterfacerendereios',['PageImpInterfaceRendereiOS',['../class_slide_over_kit_1_1_more_sample_1_1i_o_s_1_1_page_imp_interface_renderei_o_s.html',1,'SlideOverKit::MoreSample::iOS']]],
  ['pageimpinterfacerendererdroid',['PageImpInterfaceRendererDroid',['../class_slide_over_kit_1_1_more_sample_1_1_droid_1_1_page_imp_interface_renderer_droid.html',1,'SlideOverKit::MoreSample::Droid']]],
  ['pageimpinterfacerendereuwp',['PageImpInterfaceRendereUWP',['../class_slide_over_kit_1_1_more_sample_1_1_u_w_p_1_1_renderer_1_1_page_imp_interface_rendere_u_w_p.html',1,'SlideOverKit::MoreSample::UWP::Renderer']]],
  ['pairwiseseamfinder',['PairwiseSeamFinder',['../classcv_1_1detail_1_1_pairwise_seam_finder.html',1,'cv::detail']]],
  ['paniniportraitprojector',['PaniniPortraitProjector',['../structcv_1_1detail_1_1_panini_portrait_projector.html',1,'cv::detail']]],
  ['paniniportraitwarper',['PaniniPortraitWarper',['../classcv_1_1detail_1_1_panini_portrait_warper.html',1,'cv::detail::PaniniPortraitWarper'],['../classcv_1_1_panini_portrait_warper.html',1,'cv::PaniniPortraitWarper']]],
  ['paniniprojector',['PaniniProjector',['../structcv_1_1detail_1_1_panini_projector.html',1,'cv::detail']]],
  ['paniniwarper',['PaniniWarper',['../classcv_1_1detail_1_1_panini_warper.html',1,'cv::detail::PaniniWarper'],['../classcv_1_1_panini_warper.html',1,'cv::PaniniWarper']]],
  ['parallelloopbody',['ParallelLoopBody',['../classcv_1_1_parallel_loop_body.html',1,'cv']]],
  ['param',['Param',['../structcv_1_1_param.html',1,'cv']]],
  ['params',['Params',['../structcv_1_1_simple_blob_detector_1_1_params.html',1,'cv::SimpleBlobDetector']]],
  ['paramtype',['ParamType',['../structcv_1_1_param_type.html',1,'cv']]],
  ['paramtype_3c_20algorithm_20_3e',['ParamType&lt; Algorithm &gt;',['../structcv_1_1_param_type_3_01_algorithm_01_4.html',1,'cv']]],
  ['paramtype_3c_20bool_20_3e',['ParamType&lt; bool &gt;',['../structcv_1_1_param_type_3_01bool_01_4.html',1,'cv']]],
  ['paramtype_3c_20double_20_3e',['ParamType&lt; double &gt;',['../structcv_1_1_param_type_3_01double_01_4.html',1,'cv']]],
  ['paramtype_3c_20float_20_3e',['ParamType&lt; float &gt;',['../structcv_1_1_param_type_3_01float_01_4.html',1,'cv']]],
  ['paramtype_3c_20int_20_3e',['ParamType&lt; int &gt;',['../structcv_1_1_param_type_3_01int_01_4.html',1,'cv']]],
  ['paramtype_3c_20mat_20_3e',['ParamType&lt; Mat &gt;',['../structcv_1_1_param_type_3_01_mat_01_4.html',1,'cv']]],
  ['paramtype_3c_20scalar_20_3e',['ParamType&lt; Scalar &gt;',['../structcv_1_1_param_type_3_01_scalar_01_4.html',1,'cv']]],
  ['paramtype_3c_20std_3a_3avector_3c_20mat_20_3e_20_3e',['ParamType&lt; std::vector&lt; Mat &gt; &gt;',['../structcv_1_1_param_type_3_01std_1_1vector_3_01_mat_01_4_01_4.html',1,'cv']]],
  ['paramtype_3c_20string_20_3e',['ParamType&lt; String &gt;',['../structcv_1_1_param_type_3_01_string_01_4.html',1,'cv']]],
  ['paramtype_3c_20uchar_20_3e',['ParamType&lt; uchar &gt;',['../structcv_1_1_param_type_3_01uchar_01_4.html',1,'cv']]],
  ['paramtype_3c_20uint64_20_3e',['ParamType&lt; uint64 &gt;',['../structcv_1_1_param_type_3_01uint64_01_4.html',1,'cv']]],
  ['paramtype_3c_20unsigned_20_3e',['ParamType&lt; unsigned &gt;',['../structcv_1_1_param_type_3_01unsigned_01_4.html',1,'cv']]],
  ['pca',['PCA',['../classcv_1_1_p_c_a.html',1,'cv']]],
  ['permutelayer',['PermuteLayer',['../classcv_1_1dnn_1_1_permute_layer.html',1,'cv::dnn']]],
  ['photocapturedelegate',['PhotoCaptureDelegate',['../class_pix_ul8_1_1i_o_s_1_1_delegates_1_1_photo_capture_delegate.html',1,'PixUl8::iOS::Delegates']]],
  ['pixul8_5fios_5fcustomrenderers_5fcamerafeedpreviewrenderer',['PixUl8_iOS_CustomRenderers_CameraFeedPreviewRenderer',['../interface_pix_ul8__i_o_s___custom_renderers___camera_feed_preview_renderer.html',1,'']]],
  ['pixul8_5fios_5fdelegates_5fcropperdelegate',['PixUl8_iOS_Delegates_CropperDelegate',['../interface_pix_ul8__i_o_s___delegates___cropper_delegate.html',1,'']]],
  ['pixul8_5fios_5fdelegates_5fhdrphotocapturedelegate',['PixUl8_iOS_Delegates_HDRPhotoCaptureDelegate',['../interface_pix_ul8__i_o_s___delegates___h_d_r_photo_capture_delegate.html',1,'']]],
  ['pixul8_5fios_5fdelegates_5fphotocapturedelegate',['PixUl8_iOS_Delegates_PhotoCaptureDelegate',['../interface_pix_ul8__i_o_s___delegates___photo_capture_delegate.html',1,'']]],
  ['pixul8_5fios_5fdelegates_5fusernotificationcenterdelegate',['PixUl8_iOS_Delegates_UserNotificationCenterDelegate',['../interface_pix_ul8__i_o_s___delegates___user_notification_center_delegate.html',1,'']]],
  ['pixul8_5fios_5frenderers_5fadmobrenderer',['PixUl8_iOS_Renderers_AdMobRenderer',['../interface_pix_ul8__i_o_s___renderers___ad_mob_renderer.html',1,'']]],
  ['pixul8_5fios_5fservices_5fadservice',['PixUl8_iOS_Services_AdService',['../interface_pix_ul8__i_o_s___services___ad_service.html',1,'']]],
  ['pixul8_5fios_5fuiviews_5fcirclezoompercentage',['PixUl8_iOS_UIViews_CircleZoomPercentage',['../interface_pix_ul8__i_o_s___u_i_views___circle_zoom_percentage.html',1,'']]],
  ['pixul8_5fios_5fuiviews_5ffocuswheel',['PixUl8_iOS_UIViews_FocusWheel',['../interface_pix_ul8__i_o_s___u_i_views___focus_wheel.html',1,'']]],
  ['pixul8_5fios_5fuiviews_5fswipebutton',['PixUl8_iOS_UIViews_SwipeButton',['../interface_pix_ul8__i_o_s___u_i_views___swipe_button.html',1,'']]],
  ['pixul8_5fios_5fuiviews_5ftakeimagebutton',['PixUl8_iOS_UIViews_TakeImageButton',['../interface_pix_ul8__i_o_s___u_i_views___take_image_button.html',1,'']]],
  ['pixul8_5fios_5fuiviews_5fuicamerapreview',['PixUl8_iOS_UIViews_UICameraPreview',['../interface_pix_ul8__i_o_s___u_i_views___u_i_camera_preview.html',1,'']]],
  ['planeportraitprojector',['PlanePortraitProjector',['../structcv_1_1detail_1_1_plane_portrait_projector.html',1,'cv::detail']]],
  ['planeportraitwarper',['PlanePortraitWarper',['../classcv_1_1detail_1_1_plane_portrait_warper.html',1,'cv::detail']]],
  ['planeprojector',['PlaneProjector',['../structcv_1_1detail_1_1_plane_projector.html',1,'cv::detail']]],
  ['planewarper',['PlaneWarper',['../classcv_1_1detail_1_1_plane_warper.html',1,'cv::detail::PlaneWarper'],['../classcv_1_1_plane_warper.html',1,'cv::PlaneWarper']]],
  ['planewarpergpu',['PlaneWarperGpu',['../classcv_1_1detail_1_1_plane_warper_gpu.html',1,'cv::detail']]],
  ['platform',['Platform',['../classcv_1_1ocl_1_1_platform.html',1,'cv::ocl']]],
  ['platforminfo',['PlatformInfo',['../classcv_1_1ocl_1_1_platform_info.html',1,'cv::ocl']]],
  ['plugin_5ftoasts_5funnotificationmanager_5fusernotificationcenterdelegate',['Plugin_Toasts_UNNotificationManager_UserNotificationCenterDelegate',['../interface_plugin___toasts___u_n_notification_manager___user_notification_center_delegate.html',1,'']]],
  ['point3_5f',['Point3_',['../classcv_1_1_point3__.html',1,'cv']]],
  ['point_5f',['Point_',['../classcv_1_1_point__.html',1,'cv']]],
  ['point_5f_3c_20float_20_3e',['Point_&lt; float &gt;',['../classcv_1_1_point__.html',1,'cv']]],
  ['pooledallocator',['PooledAllocator',['../classcvflann_1_1_pooled_allocator.html',1,'cvflann']]],
  ['poolinglayer',['PoolingLayer',['../classcv_1_1dnn_1_1_pooling_layer.html',1,'cv::dnn']]],
  ['popoverpage',['PopOverPage',['../class_slide_over_kit_1_1_more_sample_1_1_pop_over_page.html',1,'SlideOverKit::MoreSample']]],
  ['popoverview',['PopOverView',['../class_slide_over_kit_1_1_more_sample_1_1_pop_over_view.html',1,'SlideOverKit::MoreSample']]],
  ['popoverwithtriangleview',['PopOverWithTriangleView',['../class_slide_over_kit_1_1_more_sample_1_1_pop_over_with_triangle_view.html',1,'SlideOverKit::MoreSample']]],
  ['popupviewattached',['PopupViewAttached',['../class_slide_over_kit_1_1_popup_view_attached.html',1,'SlideOverKit']]],
  ['powerlayer',['PowerLayer',['../classcv_1_1dnn_1_1_power_layer.html',1,'cv::dnn']]],
  ['priorboxlayer',['PriorBoxLayer',['../classcv_1_1dnn_1_1_prior_box_layer.html',1,'cv::dnn']]],
  ['program',['Program',['../classcv_1_1ocl_1_1_program.html',1,'cv::ocl']]],
  ['programsource',['ProgramSource',['../classcv_1_1ocl_1_1_program_source.html',1,'cv::ocl']]],
  ['projectorbase',['ProjectorBase',['../structcv_1_1detail_1_1_projector_base.html',1,'cv::detail']]],
  ['proposallayer',['ProposalLayer',['../classcv_1_1dnn_1_1_proposal_layer.html',1,'cv::dnn']]],
  ['ptr',['Ptr',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3aakaze_20_3e',['Ptr&lt; cv::AKAZE &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3abasecascadeclassifier_20_3e',['Ptr&lt; cv::BaseCascadeClassifier &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3acuda_3a_3agpumat_3a_3aallocator_20_3e',['Ptr&lt; cv::cuda::GpuMat::Allocator &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3adescriptormatcher_20_3e',['Ptr&lt; cv::DescriptorMatcher &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3adetail_3a_3ablender_20_3e',['Ptr&lt; cv::detail::Blender &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3adetail_3a_3abundleadjusterbase_20_3e',['Ptr&lt; cv::detail::BundleAdjusterBase &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3adetail_3a_3aexposurecompensator_20_3e',['Ptr&lt; cv::detail::ExposureCompensator &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3adetail_3a_3afeaturesfinder_20_3e',['Ptr&lt; cv::detail::FeaturesFinder &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3adetail_3a_3afeaturesmatcher_20_3e',['Ptr&lt; cv::detail::FeaturesMatcher &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3adetail_3a_3apairwiseseamfinder_20_3e',['Ptr&lt; cv::detail::PairwiseSeamFinder &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3adetail_3a_3aseamfinder_20_3e',['Ptr&lt; cv::detail::SeamFinder &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3afeature2d_20_3e',['Ptr&lt; cv::Feature2D &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3aorb_20_3e',['Ptr&lt; cv::ORB &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3adeblurerbase_20_3e',['Ptr&lt; cv::videostab::DeblurerBase &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3aidenseoptflowestimator_20_3e',['Ptr&lt; cv::videostab::IDenseOptFlowEstimator &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3aiframesource_20_3e',['Ptr&lt; cv::videostab::IFrameSource &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3ailog_20_3e',['Ptr&lt; cv::videostab::ILog &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3aimagemotionestimatorbase_20_3e',['Ptr&lt; cv::videostab::ImageMotionEstimatorBase &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3aimotionstabilizer_20_3e',['Ptr&lt; cv::videostab::IMotionStabilizer &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3ainpainterbase_20_3e',['Ptr&lt; cv::videostab::InpainterBase &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3aioutlierrejector_20_3e',['Ptr&lt; cv::videostab::IOutlierRejector &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3aisparseoptflowestimator_20_3e',['Ptr&lt; cv::videostab::ISparseOptFlowEstimator &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3amotionestimatorbase_20_3e',['Ptr&lt; cv::videostab::MotionEstimatorBase &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3amotionfilterbase_20_3e',['Ptr&lt; cv::videostab::MotionFilterBase &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3avideostab_3a_3awobblesuppressorbase_20_3e',['Ptr&lt; cv::videostab::WobbleSuppressorBase &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cv_3a_3awarpercreator_20_3e',['Ptr&lt; cv::WarperCreator &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cvcapture_20_3e',['Ptr&lt; CvCapture &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cvfilestorage_20_3e',['Ptr&lt; CvFileStorage &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20cvvideowriter_20_3e',['Ptr&lt; CvVideoWriter &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20impl_20_3e',['Ptr&lt; Impl &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20ivideocapture_20_3e',['Ptr&lt; IVideoCapture &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['ptr_3c_20ivideowriter_20_3e',['Ptr&lt; IVideoWriter &gt;',['../structcv_1_1_ptr.html',1,'cv']]],
  ['pyrlkoptflowestimatorbase',['PyrLkOptFlowEstimatorBase',['../classcv_1_1videostab_1_1_pyr_lk_opt_flow_estimator_base.html',1,'cv::videostab']]]
];
