var searchData=
[
  ['abslayer',['AbsLayer',['../classcv_1_1dnn_1_1_abs_layer.html',1,'cv::dnn']]],
  ['accumulator',['Accumulator',['../structcv_1_1_accumulator.html',1,'cv::Accumulator&lt; T &gt;'],['../structcvflann_1_1_accumulator.html',1,'cvflann::Accumulator&lt; T &gt;']]],
  ['accumulator_3c_20char_20_3e',['Accumulator&lt; char &gt;',['../structcv_1_1_accumulator_3_01char_01_4.html',1,'cv::Accumulator&lt; char &gt;'],['../structcvflann_1_1_accumulator_3_01char_01_4.html',1,'cvflann::Accumulator&lt; char &gt;']]],
  ['accumulator_3c_20int_20_3e',['Accumulator&lt; int &gt;',['../structcvflann_1_1_accumulator_3_01int_01_4.html',1,'cvflann']]],
  ['accumulator_3c_20short_20_3e',['Accumulator&lt; short &gt;',['../structcv_1_1_accumulator_3_01short_01_4.html',1,'cv::Accumulator&lt; short &gt;'],['../structcvflann_1_1_accumulator_3_01short_01_4.html',1,'cvflann::Accumulator&lt; short &gt;']]],
  ['accumulator_3c_20unsigned_20char_20_3e',['Accumulator&lt; unsigned char &gt;',['../structcv_1_1_accumulator_3_01unsigned_01char_01_4.html',1,'cv::Accumulator&lt; unsigned char &gt;'],['../structcvflann_1_1_accumulator_3_01unsigned_01char_01_4.html',1,'cvflann::Accumulator&lt; unsigned char &gt;']]],
  ['accumulator_3c_20unsigned_20int_20_3e',['Accumulator&lt; unsigned int &gt;',['../structcvflann_1_1_accumulator_3_01unsigned_01int_01_4.html',1,'cvflann']]],
  ['accumulator_3c_20unsigned_20short_20_3e',['Accumulator&lt; unsigned short &gt;',['../structcv_1_1_accumulator_3_01unsigned_01short_01_4.html',1,'cv::Accumulator&lt; unsigned short &gt;'],['../structcvflann_1_1_accumulator_3_01unsigned_01short_01_4.html',1,'cvflann::Accumulator&lt; unsigned short &gt;']]],
  ['activationlayer',['ActivationLayer',['../classcv_1_1dnn_1_1_activation_layer.html',1,'cv::dnn']]],
  ['admobrenderer',['AdMobRenderer',['../class_pix_ul8_1_1i_o_s_1_1_renderers_1_1_ad_mob_renderer.html',1,'PixUl8::iOS::Renderers']]],
  ['admobview',['AdMobView',['../class_pix_ul8_1_1_views_1_1_ad_mob_view.html',1,'PixUl8::Views']]],
  ['adservice',['AdService',['../class_pix_ul8_1_1i_o_s_1_1_services_1_1_ad_service.html',1,'PixUl8::iOS::Services']]],
  ['affinebasedestimator',['AffineBasedEstimator',['../classcv_1_1detail_1_1_affine_based_estimator.html',1,'cv::detail']]],
  ['affinebestof2nearestmatcher',['AffineBestOf2NearestMatcher',['../classcv_1_1detail_1_1_affine_best_of2_nearest_matcher.html',1,'cv::detail']]],
  ['affinetransformer',['AffineTransformer',['../classcv_1_1_affine_transformer.html',1,'cv']]],
  ['affinewarper',['AffineWarper',['../classcv_1_1detail_1_1_affine_warper.html',1,'cv::detail::AffineWarper'],['../classcv_1_1_affine_warper.html',1,'cv::AffineWarper']]],
  ['agastfeaturedetector',['AgastFeatureDetector',['../classcv_1_1_agast_feature_detector.html',1,'cv']]],
  ['aidatepickercontroller',['AIDatePickerController',['../interface_a_i_date_picker_controller.html',1,'']]],
  ['akaze',['AKAZE',['../classcv_1_1_a_k_a_z_e.html',1,'cv']]],
  ['akazefeaturesfinder',['AKAZEFeaturesFinder',['../classcv_1_1detail_1_1_a_k_a_z_e_features_finder.html',1,'cv::detail']]],
  ['algorithm',['Algorithm',['../classcv_1_1_algorithm.html',1,'cv']]],
  ['alignexposures',['AlignExposures',['../classcv_1_1_align_exposures.html',1,'cv']]],
  ['alignmtb',['AlignMTB',['../classcv_1_1_align_m_t_b.html',1,'cv']]],
  ['allocator',['Allocator',['../classcv_1_1cuda_1_1_gpu_mat_1_1_allocator.html',1,'cv::cuda::GpuMat::Allocator'],['../classcv_1_1_allocator.html',1,'cv::Allocator&lt; _Tp &gt;']]],
  ['animation',['Animation',['../class_slide_over_kit_1_1_more_sample_1_1_droid_1_1_resource_1_1_animation.html',1,'SlideOverKit::MoreSample::Droid::Resource']]],
  ['animator',['Animator',['../class_slide_over_kit_1_1_more_sample_1_1_droid_1_1_resource_1_1_animator.html',1,'SlideOverKit::MoreSample::Droid::Resource']]],
  ['animatorlistener',['AnimatorListener',['../class_slide_over_kit_1_1_droid_1_1_animator_listener.html',1,'SlideOverKit::Droid']]],
  ['any',['any',['../structcvflann_1_1any.html',1,'cvflann']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fadloaderdelegate',['ApiDefinition__Google_MobileAds_AdLoaderDelegate',['../interface_api_definition_____google___mobile_ads___ad_loader_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fadnetworkextras',['ApiDefinition__Google_MobileAds_AdNetworkExtras',['../interface_api_definition_____google___mobile_ads___ad_network_extras.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fadsizedelegate',['ApiDefinition__Google_MobileAds_AdSizeDelegate',['../interface_api_definition_____google___mobile_ads___ad_size_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fappeventdelegate',['ApiDefinition__Google_MobileAds_AppEventDelegate',['../interface_api_definition_____google___mobile_ads___app_event_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5faudiovideomanagerdelegate',['ApiDefinition__Google_MobileAds_AudioVideoManagerDelegate',['../interface_api_definition_____google___mobile_ads___audio_video_manager_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fbannerviewdelegate',['ApiDefinition__Google_MobileAds_BannerViewDelegate',['../interface_api_definition_____google___mobile_ads___banner_view_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fcustomeventbannerdelegate',['ApiDefinition__Google_MobileAds_CustomEventBannerDelegate',['../interface_api_definition_____google___mobile_ads___custom_event_banner_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fcustomeventinterstitialdelegate',['ApiDefinition__Google_MobileAds_CustomEventInterstitialDelegate',['../interface_api_definition_____google___mobile_ads___custom_event_interstitial_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fcustomeventnativead',['ApiDefinition__Google_MobileAds_CustomEventNativeAd',['../interface_api_definition_____google___mobile_ads___custom_event_native_ad.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fcustomeventnativeaddelegate',['ApiDefinition__Google_MobileAds_CustomEventNativeAdDelegate',['../interface_api_definition_____google___mobile_ads___custom_event_native_ad_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fdebugoptionsviewcontrollerdelegate',['ApiDefinition__Google_MobileAds_DebugOptionsViewControllerDelegate',['../interface_api_definition_____google___mobile_ads___debug_options_view_controller_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fdefaultinapppurchasedelegate',['ApiDefinition__Google_MobileAds_DefaultInAppPurchaseDelegate',['../interface_api_definition_____google___mobile_ads___default_in_app_purchase_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fdoubleclick_5fbanneradloaderdelegate',['ApiDefinition__Google_MobileAds_DoubleClick_BannerAdLoaderDelegate',['../interface_api_definition_____google___mobile_ads___double_click___banner_ad_loader_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fdoubleclick_5fcustomrenderedbannerviewdelegate',['ApiDefinition__Google_MobileAds_DoubleClick_CustomRenderedBannerViewDelegate',['../interface_api_definition_____google___mobile_ads___double_click___custom_rendered_banner_view_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fdoubleclick_5fcustomrenderedinterstitialdelegate',['ApiDefinition__Google_MobileAds_DoubleClick_CustomRenderedInterstitialDelegate',['../interface_api_definition_____google___mobile_ads___double_click___custom_rendered_interstitial_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5finapppurchasedelegate',['ApiDefinition__Google_MobileAds_InAppPurchaseDelegate',['../interface_api_definition_____google___mobile_ads___in_app_purchase_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5finterstitialdelegate',['ApiDefinition__Google_MobileAds_InterstitialDelegate',['../interface_api_definition_____google___mobile_ads___interstitial_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fmediatednativead',['ApiDefinition__Google_MobileAds_MediatedNativeAd',['../interface_api_definition_____google___mobile_ads___mediated_native_ad.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fmediatednativeaddelegate',['ApiDefinition__Google_MobileAds_MediatedNativeAdDelegate',['../interface_api_definition_____google___mobile_ads___mediated_native_ad_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fmediatednativeappinstallad',['ApiDefinition__Google_MobileAds_MediatedNativeAppInstallAd',['../interface_api_definition_____google___mobile_ads___mediated_native_app_install_ad.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fmediatednativecontentad',['ApiDefinition__Google_MobileAds_MediatedNativeContentAd',['../interface_api_definition_____google___mobile_ads___mediated_native_content_ad.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fmediation_5fmediatedunifiednativead',['ApiDefinition__Google_MobileAds_Mediation_MediatedUnifiedNativeAd',['../interface_api_definition_____google___mobile_ads___mediation___mediated_unified_native_ad.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fnativeaddelegate',['ApiDefinition__Google_MobileAds_NativeAdDelegate',['../interface_api_definition_____google___mobile_ads___native_ad_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fnativeappinstalladloaderdelegate',['ApiDefinition__Google_MobileAds_NativeAppInstallAdLoaderDelegate',['../interface_api_definition_____google___mobile_ads___native_app_install_ad_loader_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fnativecontentadloaderdelegate',['ApiDefinition__Google_MobileAds_NativeContentAdLoaderDelegate',['../interface_api_definition_____google___mobile_ads___native_content_ad_loader_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fnativecustomtemplateadloaderdelegate',['ApiDefinition__Google_MobileAds_NativeCustomTemplateAdLoaderDelegate',['../interface_api_definition_____google___mobile_ads___native_custom_template_ad_loader_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fnativeexpressadviewdelegate',['ApiDefinition__Google_MobileAds_NativeExpressAdViewDelegate',['../interface_api_definition_____google___mobile_ads___native_express_ad_view_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5frewardbasedvideoaddelegate',['ApiDefinition__Google_MobileAds_RewardBasedVideoAdDelegate',['../interface_api_definition_____google___mobile_ads___reward_based_video_ad_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fswipeablebannerviewdelegate',['ApiDefinition__Google_MobileAds_SwipeableBannerViewDelegate',['../interface_api_definition_____google___mobile_ads___swipeable_banner_view_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5funifiednativeaddelegate',['ApiDefinition__Google_MobileAds_UnifiedNativeAdDelegate',['../interface_api_definition_____google___mobile_ads___unified_native_ad_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5funifiednativeadloaderdelegate',['ApiDefinition__Google_MobileAds_UnifiedNativeAdLoaderDelegate',['../interface_api_definition_____google___mobile_ads___unified_native_ad_loader_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5funifiednativeadunconfirmedclickdelegate',['ApiDefinition__Google_MobileAds_UnifiedNativeAdUnconfirmedClickDelegate',['../interface_api_definition_____google___mobile_ads___unified_native_ad_unconfirmed_click_delegate.html',1,'']]],
  ['apidefinition_5f_5fgoogle_5fmobileads_5fvideocontrollerdelegate',['ApiDefinition__Google_MobileAds_VideoControllerDelegate',['../interface_api_definition_____google___mobile_ads___video_controller_delegate.html',1,'']]],
  ['app',['App',['../class_slide_over_kit_1_1_more_sample_1_1_u_w_p_1_1_app.html',1,'SlideOverKit.MoreSample.UWP.App'],['../class_slide_over_kit_1_1_more_sample_1_1_app.html',1,'SlideOverKit.MoreSample.App'],['../class_pix_ul8_1_1_app.html',1,'PixUl8.App']]],
  ['appdelegate',['AppDelegate',['../class_slide_over_kit_1_1_more_sample_1_1i_o_s_1_1_app_delegate.html',1,'SlideOverKit.MoreSample.iOS.AppDelegate'],['../class_pix_ul8_1_1i_o_s_1_1_app_delegate.html',1,'PixUl8.iOS.AppDelegate'],['../interface_app_delegate.html',1,'AppDelegate']]],
  ['appinitializer',['AppInitializer',['../class_slide_over_kit_1_1_sample_1_1_u_i_tests_1_1_app_initializer.html',1,'SlideOverKit::Sample::UITests']]],
  ['application',['Application',['../class_slide_over_kit_1_1_more_sample_1_1i_o_s_1_1_application.html',1,'SlideOverKit.MoreSample.iOS.Application'],['../class_pix_ul8_1_1i_o_s_1_1_application.html',1,'PixUl8.iOS.Application']]],
  ['arrays',['Arrays',['../classcv_1_1ogl_1_1_arrays.html',1,'cv::ogl']]],
  ['attribute',['Attribute',['../class_slide_over_kit_1_1_more_sample_1_1_droid_1_1_resource_1_1_attribute.html',1,'SlideOverKit::MoreSample::Droid::Resource']]],
  ['autobuffer',['AutoBuffer',['../classcv_1_1_auto_buffer.html',1,'cv']]],
  ['autobuffer_3c_20cv_3a_3astring_2c_201_20_3e',['AutoBuffer&lt; cv::String, 1 &gt;',['../classcv_1_1_auto_buffer.html',1,'cv']]],
  ['autobuffer_3c_20double_2c_201_20_3e',['AutoBuffer&lt; double, 1 &gt;',['../classcv_1_1_auto_buffer.html',1,'cv']]],
  ['autobuffer_3c_20int64_2c_201_20_3e',['AutoBuffer&lt; int64, 1 &gt;',['../classcv_1_1_auto_buffer.html',1,'cv']]],
  ['autogeneratedprogram',['AutoGeneratedProgram',['../class_auto_generated_program.html',1,'']]],
  ['autolock',['AutoLock',['../classcv_1_1_auto_lock.html',1,'cv']]],
  ['autotunedindex',['AutotunedIndex',['../classcvflann_1_1_autotuned_index.html',1,'cvflann']]],
  ['autotunedindexparams',['AutotunedIndexParams',['../structcvflann_1_1_autotuned_index_params.html',1,'cvflann::AutotunedIndexParams'],['../structcv_1_1flann_1_1_autotuned_index_params.html',1,'cv::flann::AutotunedIndexParams']]],
  ['avcapturephotocapturedelegate',['AVCapturePhotoCaptureDelegate',['../interface_a_v_capture_photo_capture_delegate.html',1,'']]]
];
