var searchData=
[
  ['safefmt',['SafeFmt',['../structcv_1_1traits_1_1_safe_fmt.html',1,'cv::traits']]],
  ['safefmt_3c_20t_2c_20false_20_3e',['SafeFmt&lt; T, false &gt;',['../structcv_1_1traits_1_1_safe_fmt_3_01_t_00_01false_01_4.html',1,'cv::traits']]],
  ['safefmt_3c_20t_2c_20true_20_3e',['SafeFmt&lt; T, true &gt;',['../structcv_1_1traits_1_1_safe_fmt_3_01_t_00_01true_01_4.html',1,'cv::traits']]],
  ['safetype',['SafeType',['../structcv_1_1traits_1_1_safe_type.html',1,'cv::traits']]],
  ['safetype_3c_20t_2c_20false_20_3e',['SafeType&lt; T, false &gt;',['../structcv_1_1traits_1_1_safe_type_3_01_t_00_01false_01_4.html',1,'cv::traits']]],
  ['safetype_3c_20t_2c_20true_20_3e',['SafeType&lt; T, true &gt;',['../structcv_1_1traits_1_1_safe_type_3_01_t_00_01true_01_4.html',1,'cv::traits']]],
  ['savedindexparams',['SavedIndexParams',['../structcv_1_1flann_1_1_saved_index_params.html',1,'cv::flann::SavedIndexParams'],['../structcvflann_1_1_saved_index_params.html',1,'cvflann::SavedIndexParams']]],
  ['scalar_5f',['Scalar_',['../classcv_1_1_scalar__.html',1,'cv']]],
  ['scalar_5f_3c_20double_20_3e',['Scalar_&lt; double &gt;',['../classcv_1_1_scalar__.html',1,'cv']]],
  ['scalelayer',['ScaleLayer',['../classcv_1_1dnn_1_1_scale_layer.html',1,'cv::dnn']]],
  ['seamfinder',['SeamFinder',['../classcv_1_1detail_1_1_seam_finder.html',1,'cv::detail']]],
  ['searchparams',['SearchParams',['../structcv_1_1flann_1_1_search_params.html',1,'cv::flann::SearchParams'],['../structcvflann_1_1_search_params.html',1,'cvflann::SearchParams']]],
  ['seqreader',['SeqReader',['../structcv_1_1_file_node_iterator_1_1_seq_reader.html',1,'cv::FileNodeIterator']]],
  ['settingsservice',['SettingsService',['../class_pix_ul8_1_1_services_1_1_settings_service.html',1,'PixUl8::Services']]],
  ['shapecontextdistanceextractor',['ShapeContextDistanceExtractor',['../classcv_1_1_shape_context_distance_extractor.html',1,'cv']]],
  ['shapedistanceextractor',['ShapeDistanceExtractor',['../classcv_1_1_shape_distance_extractor.html',1,'cv']]],
  ['shapetransformer',['ShapeTransformer',['../classcv_1_1_shape_transformer.html',1,'cv']]],
  ['shiftlayer',['ShiftLayer',['../classcv_1_1dnn_1_1_shift_layer.html',1,'cv::dnn']]],
  ['shufflechannellayer',['ShuffleChannelLayer',['../classcv_1_1dnn_1_1_shuffle_channel_layer.html',1,'cv::dnn']]],
  ['siftfeaturesfinder',['SiftFeaturesFinder',['../classcv_1_1detail_1_1_sift_features_finder.html',1,'cv::detail']]],
  ['sigmoidlayer',['SigmoidLayer',['../classcv_1_1dnn_1_1_sigmoid_layer.html',1,'cv::dnn']]],
  ['similarrects',['SimilarRects',['../classcv_1_1_similar_rects.html',1,'cv']]],
  ['simpleblobdetector',['SimpleBlobDetector',['../classcv_1_1_simple_blob_detector.html',1,'cv']]],
  ['simpledistance',['simpleDistance',['../structcvflann_1_1simple_distance.html',1,'cvflann']]],
  ['simpledistance_3c_20chisquaredistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; ChiSquareDistance&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1simple_distance_3_01_chi_square_distance_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20hellingerdistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; HellingerDistance&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1simple_distance_3_01_hellinger_distance_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20l2_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; L2&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1simple_distance_3_01_l2_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20l2_5fsimple_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; L2_Simple&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1simple_distance_3_01_l2___simple_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20minkowskidistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; MinkowskiDistance&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1simple_distance_3_01_minkowski_distance_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['singlepolicy',['SinglePolicy',['../classcvflann_1_1anyimpl_1_1_single_policy.html',1,'cvflann::anyimpl']]],
  ['size_5f',['Size_',['../classcv_1_1_size__.html',1,'cv']]],
  ['size_5f_3c_20float_20_3e',['Size_&lt; float &gt;',['../classcv_1_1_size__.html',1,'cv']]],
  ['sl2',['SL2',['../structcv_1_1_s_l2.html',1,'cv']]],
  ['slicelayer',['SliceLayer',['../classcv_1_1dnn_1_1_slice_layer.html',1,'cv::dnn']]],
  ['slidedownmenupage',['SlideDownMenuPage',['../class_slide_over_kit_1_1_more_sample_1_1_slide_down_menu_page.html',1,'SlideOverKit::MoreSample']]],
  ['slidedownmenuview',['SlideDownMenuView',['../class_slide_over_kit_1_1_more_sample_1_1_slide_down_menu_view.html',1,'SlideOverKit::MoreSample']]],
  ['slidemenudroidrenderer',['SlideMenuDroidRenderer',['../class_slide_over_kit_1_1_droid_1_1_slide_menu_droid_renderer.html',1,'SlideOverKit::Droid']]],
  ['slidemenuupview',['SlideMenuUpView',['../class_pix_ul8_1_1_views_1_1_extension_views_1_1_slide_menu_up_view.html',1,'PixUl8::Views::ExtensionViews']]],
  ['slidemenuview',['SlideMenuView',['../class_slide_over_kit_1_1_slide_menu_view.html',1,'SlideOverKit']]],
  ['slideoverkit',['SlideOverKit',['../class_slide_over_kit_1_1i_o_s_1_1_slide_over_kit.html',1,'SlideOverKit::iOS']]],
  ['slideoverkit_5fios_5fmenucontainerpageiosrenderer',['SlideOverKit_iOS_MenuContainerPageiOSRenderer',['../interface_slide_over_kit__i_o_s___menu_container_pagei_o_s_renderer.html',1,'']]],
  ['slideoverkit_5fios_5fslidepopupviewrendererios',['SlideOverKit_iOS_SlidePopupViewRendereriOS',['../interface_slide_over_kit__i_o_s___slide_popup_view_rendereri_o_s.html',1,'']]],
  ['slideoverkitdroidhandler',['SlideOverKitDroidHandler',['../class_slide_over_kit_1_1_droid_1_1_slide_over_kit_droid_handler.html',1,'SlideOverKit::Droid']]],
  ['slideoverkitioshandler',['SlideOverKitiOSHandler',['../class_slide_over_kit_1_1i_o_s_1_1_slide_over_kiti_o_s_handler.html',1,'SlideOverKit::iOS']]],
  ['slideoverkituwphandler',['SlideOverKitUWPHandler',['../class_slide_over_kit_1_1_u_w_p_1_1_slide_over_kit_u_w_p_handler.html',1,'SlideOverKit::UWP']]],
  ['slidepopupview',['SlidePopupView',['../class_slide_over_kit_1_1_slide_popup_view.html',1,'SlideOverKit']]],
  ['slidepopupviewrendererdroid',['SlidePopupViewRendererDroid',['../class_slide_over_kit_1_1_droid_1_1_slide_popup_view_renderer_droid.html',1,'SlideOverKit::Droid']]],
  ['slidepopupviewrendererios',['SlidePopupViewRendereriOS',['../class_slide_over_kit_1_1i_o_s_1_1_slide_popup_view_rendereri_o_s.html',1,'SlideOverKit::iOS']]],
  ['slideupmenupage',['SlideUpMenuPage',['../class_slide_over_kit_1_1_more_sample_1_1_slide_up_menu_page.html',1,'SlideOverKit::MoreSample']]],
  ['slideupmenuview',['SlideUpMenuView',['../class_slide_over_kit_1_1_more_sample_1_1_slide_up_menu_view.html',1,'SlideOverKit::MoreSample']]],
  ['slideupview',['SlideUpView',['../class_pix_ul8_1_1_views_1_1_extension_views_1_1_slide_up_view.html',1,'PixUl8::Views::ExtensionViews']]],
  ['softdouble',['softdouble',['../structcv_1_1softdouble.html',1,'cv']]],
  ['softfloat',['softfloat',['../structcv_1_1softfloat.html',1,'cv']]],
  ['softmaxlayer',['SoftmaxLayer',['../classcv_1_1dnn_1_1_softmax_layer.html',1,'cv::dnn']]],
  ['sparsemat',['SparseMat',['../classcv_1_1_sparse_mat.html',1,'cv']]],
  ['sparsemat_5f',['SparseMat_',['../classcv_1_1_sparse_mat__.html',1,'cv']]],
  ['sparsematconstiterator',['SparseMatConstIterator',['../classcv_1_1_sparse_mat_const_iterator.html',1,'cv']]],
  ['sparsematconstiterator_5f',['SparseMatConstIterator_',['../classcv_1_1_sparse_mat_const_iterator__.html',1,'cv']]],
  ['sparsematiterator',['SparseMatIterator',['../classcv_1_1_sparse_mat_iterator.html',1,'cv']]],
  ['sparsematiterator_5f',['SparseMatIterator_',['../classcv_1_1_sparse_mat_iterator__.html',1,'cv']]],
  ['sparseopticalflow',['SparseOpticalFlow',['../classcv_1_1_sparse_optical_flow.html',1,'cv']]],
  ['sparsepyrlkoptflowestimator',['SparsePyrLkOptFlowEstimator',['../classcv_1_1videostab_1_1_sparse_pyr_lk_opt_flow_estimator.html',1,'cv::videostab']]],
  ['sparsepyrlkopticalflow',['SparsePyrLKOpticalFlow',['../classcv_1_1_sparse_pyr_l_k_optical_flow.html',1,'cv']]],
  ['sphericalportraitprojector',['SphericalPortraitProjector',['../structcv_1_1detail_1_1_spherical_portrait_projector.html',1,'cv::detail']]],
  ['sphericalportraitwarper',['SphericalPortraitWarper',['../classcv_1_1detail_1_1_spherical_portrait_warper.html',1,'cv::detail']]],
  ['sphericalprojector',['SphericalProjector',['../structcv_1_1detail_1_1_spherical_projector.html',1,'cv::detail']]],
  ['sphericalwarper',['SphericalWarper',['../classcv_1_1detail_1_1_spherical_warper.html',1,'cv::detail::SphericalWarper'],['../classcv_1_1_spherical_warper.html',1,'cv::SphericalWarper']]],
  ['sphericalwarpergpu',['SphericalWarperGpu',['../classcv_1_1detail_1_1_spherical_warper_gpu.html',1,'cv::detail']]],
  ['splitlayer',['SplitLayer',['../classcv_1_1dnn_1_1_split_layer.html',1,'cv::dnn']]],
  ['squaredistance',['squareDistance',['../structcvflann_1_1square_distance.html',1,'cvflann']]],
  ['squaredistance_3c_20chisquaredistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; ChiSquareDistance&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1square_distance_3_01_chi_square_distance_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20hellingerdistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; HellingerDistance&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1square_distance_3_01_hellinger_distance_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20l2_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; L2&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1square_distance_3_01_l2_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20l2_5fsimple_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; L2_Simple&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1square_distance_3_01_l2___simple_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20minkowskidistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; MinkowskiDistance&lt; ElementType &gt;, ElementType &gt;',['../structcvflann_1_1square_distance_3_01_minkowski_distance_3_01_element_type_01_4_00_01_element_type_01_4.html',1,'cvflann']]],
  ['stabilizerbase',['StabilizerBase',['../classcv_1_1videostab_1_1_stabilizer_base.html',1,'cv::videostab']]],
  ['startstoptimer',['StartStopTimer',['../classcvflann_1_1_start_stop_timer.html',1,'cvflann']]],
  ['stereobm',['StereoBM',['../classcv_1_1_stereo_b_m.html',1,'cv']]],
  ['stereographicprojector',['StereographicProjector',['../structcv_1_1detail_1_1_stereographic_projector.html',1,'cv::detail']]],
  ['stereographicwarper',['StereographicWarper',['../classcv_1_1detail_1_1_stereographic_warper.html',1,'cv::detail::StereographicWarper'],['../classcv_1_1_stereographic_warper.html',1,'cv::StereographicWarper']]],
  ['stereomatcher',['StereoMatcher',['../classcv_1_1_stereo_matcher.html',1,'cv']]],
  ['stereosgbm',['StereoSGBM',['../classcv_1_1_stereo_s_g_b_m.html',1,'cv']]],
  ['stitcher',['Stitcher',['../classcv_1_1_stitcher.html',1,'cv']]],
  ['stream',['Stream',['../classcv_1_1cuda_1_1_stream.html',1,'cv::cuda']]],
  ['streamaccessor',['StreamAccessor',['../structcv_1_1cuda_1_1_stream_accessor.html',1,'cv::cuda']]],
  ['string',['String',['../class_slide_over_kit_1_1_more_sample_1_1_droid_1_1_resource_1_1_string.html',1,'SlideOverKit.MoreSample.Droid.Resource.String'],['../classcv_1_1_string.html',1,'cv::String']]],
  ['style',['Style',['../class_slide_over_kit_1_1_more_sample_1_1_droid_1_1_resource_1_1_style.html',1,'SlideOverKit::MoreSample::Droid::Resource']]],
  ['styleable',['Styleable',['../class_slide_over_kit_1_1_more_sample_1_1_droid_1_1_resource_1_1_styleable.html',1,'SlideOverKit::MoreSample::Droid::Resource']]],
  ['subdiv2d',['Subdiv2D',['../classcv_1_1_subdiv2_d.html',1,'cv']]],
  ['surffeaturesfinder',['SurfFeaturesFinder',['../classcv_1_1detail_1_1_surf_features_finder.html',1,'cv::detail']]],
  ['svd',['SVD',['../classcv_1_1_s_v_d.html',1,'cv']]],
  ['swipebutton',['SwipeButton',['../class_pix_ul8_1_1i_o_s_1_1_u_i_views_1_1_swipe_button.html',1,'PixUl8::iOS::UIViews']]]
];
