var searchData=
[
  ['mainactivity',['MainActivity',['../class_menu_kit_1_1_sample_1_1_droid_1_1_main_activity.html',1,'MenuKit::Sample::Droid']]],
  ['mainpage',['MainPage',['../class_slide_over_kit_1_1_more_sample_1_1_u_w_p_1_1_main_page.html',1,'SlideOverKit.MoreSample.UWP.MainPage'],['../class_slide_over_kit_1_1_more_sample_1_1_main_page.html',1,'SlideOverKit.MoreSample.MainPage']]],
  ['maskgenerator',['MaskGenerator',['../classcv_1_1_base_cascade_classifier_1_1_mask_generator.html',1,'cv::BaseCascadeClassifier']]],
  ['mat',['Mat',['../classcv_1_1_mat.html',1,'cv']]],
  ['mat_5f',['Mat_',['../classcv_1_1_mat__.html',1,'cv']]],
  ['mat_5f_3c_20double_20_3e',['Mat_&lt; double &gt;',['../classcv_1_1_mat__.html',1,'cv']]],
  ['mat_5f_3c_20float_20_3e',['Mat_&lt; float &gt;',['../classcv_1_1_mat__.html',1,'cv']]],
  ['mat_5f_3c_20int_20_3e',['Mat_&lt; int &gt;',['../classcv_1_1_mat__.html',1,'cv']]],
  ['mat_5f_3c_20uchar_20_3e',['Mat_&lt; uchar &gt;',['../classcv_1_1_mat__.html',1,'cv']]],
  ['matallocator',['MatAllocator',['../classcv_1_1_mat_allocator.html',1,'cv']]],
  ['matchesinfo',['MatchesInfo',['../structcv_1_1detail_1_1_matches_info.html',1,'cv::detail']]],
  ['matcommainitializer_5f',['MatCommaInitializer_',['../classcv_1_1_mat_comma_initializer__.html',1,'cv']]],
  ['matconstiterator',['MatConstIterator',['../classcv_1_1_mat_const_iterator.html',1,'cv']]],
  ['matconstiterator_5f',['MatConstIterator_',['../classcv_1_1_mat_const_iterator__.html',1,'cv']]],
  ['matexpr',['MatExpr',['../classcv_1_1_mat_expr.html',1,'cv']]],
  ['matiterator_5f',['MatIterator_',['../classcv_1_1_mat_iterator__.html',1,'cv']]],
  ['matop',['MatOp',['../classcv_1_1_mat_op.html',1,'cv']]],
  ['matrix',['Matrix',['../classcvflann_1_1_matrix.html',1,'cvflann']]],
  ['matrix_3c_20double_20_3e',['Matrix&lt; double &gt;',['../classcvflann_1_1_matrix.html',1,'cvflann']]],
  ['matrix_3c_20elementtype_20_3e',['Matrix&lt; ElementType &gt;',['../classcvflann_1_1_matrix.html',1,'cvflann']]],
  ['matrix_3c_20int_20_3e',['Matrix&lt; int &gt;',['../classcvflann_1_1_matrix.html',1,'cvflann']]],
  ['matsize',['MatSize',['../structcv_1_1_mat_size.html',1,'cv']]],
  ['matstep',['MatStep',['../structcv_1_1_mat_step.html',1,'cv']]],
  ['matx',['Matx',['../classcv_1_1_matx.html',1,'cv']]],
  ['matx_3c_20_5ftp_2c_20cn_2c_201_20_3e',['Matx&lt; _Tp, cn, 1 &gt;',['../classcv_1_1_matx.html',1,'cv']]],
  ['matx_3c_20double_2c_20cn_2c_201_20_3e',['Matx&lt; double, cn, 1 &gt;',['../classcv_1_1_matx.html',1,'cv']]],
  ['matxcommainitializer',['MatxCommaInitializer',['../classcv_1_1_matx_comma_initializer.html',1,'cv']]],
  ['matxcommainitializer_3c_20_5ftp_2c_20m_2c_201_20_3e',['MatxCommaInitializer&lt; _Tp, m, 1 &gt;',['../classcv_1_1_matx_comma_initializer.html',1,'cv']]],
  ['maxdistance',['MaxDistance',['../structcvflann_1_1_max_distance.html',1,'cvflann']]],
  ['maxunpoollayer',['MaxUnpoolLayer',['../classcv_1_1dnn_1_1_max_unpool_layer.html',1,'cv::dnn']]],
  ['menucontainerpage',['MenuContainerPage',['../class_slide_over_kit_1_1_menu_container_page.html',1,'SlideOverKit']]],
  ['menucontainerpagedroidrenderer',['MenuContainerPageDroidRenderer',['../class_slide_over_kit_1_1_droid_1_1_menu_container_page_droid_renderer.html',1,'SlideOverKit::Droid']]],
  ['menucontainerpageiosrenderer',['MenuContainerPageiOSRenderer',['../class_slide_over_kit_1_1i_o_s_1_1_menu_container_pagei_o_s_renderer.html',1,'SlideOverKit::iOS']]],
  ['menucontainerpageuwprenderer',['MenuContainerPageUWPRenderer',['../class_slide_over_kit_1_1_u_w_p_1_1_menu_container_page_u_w_p_renderer.html',1,'SlideOverKit::UWP']]],
  ['mercatorprojector',['MercatorProjector',['../structcv_1_1detail_1_1_mercator_projector.html',1,'cv::detail']]],
  ['mercatorwarper',['MercatorWarper',['../classcv_1_1_mercator_warper.html',1,'cv::MercatorWarper'],['../classcv_1_1detail_1_1_mercator_warper.html',1,'cv::detail::MercatorWarper']]],
  ['mergedebevec',['MergeDebevec',['../classcv_1_1_merge_debevec.html',1,'cv']]],
  ['mergeexposures',['MergeExposures',['../classcv_1_1_merge_exposures.html',1,'cv']]],
  ['mergemertens',['MergeMertens',['../classcv_1_1_merge_mertens.html',1,'cv']]],
  ['mergerobertson',['MergeRobertson',['../classcv_1_1_merge_robertson.html',1,'cv']]],
  ['metadataobjectdelegate',['MetaDataObjectDelegate',['../class_pix_ul8_1_1i_o_s_1_1_models_1_1_meta_data_object_delegate.html',1,'PixUl8::iOS::Models']]],
  ['minkowskidistance',['MinkowskiDistance',['../structcvflann_1_1_minkowski_distance.html',1,'cvflann']]],
  ['minproblemsolver',['MinProblemSolver',['../classcv_1_1_min_problem_solver.html',1,'cv']]],
  ['moments',['Moments',['../classcv_1_1_moments.html',1,'cv']]],
  ['moreaccuratemotionwobblesuppressor',['MoreAccurateMotionWobbleSuppressor',['../classcv_1_1videostab_1_1_more_accurate_motion_wobble_suppressor.html',1,'cv::videostab']]],
  ['moreaccuratemotionwobblesuppressorbase',['MoreAccurateMotionWobbleSuppressorBase',['../classcv_1_1videostab_1_1_more_accurate_motion_wobble_suppressor_base.html',1,'cv::videostab']]],
  ['motionestimatorbase',['MotionEstimatorBase',['../classcv_1_1videostab_1_1_motion_estimator_base.html',1,'cv::videostab']]],
  ['motionestimatorl1',['MotionEstimatorL1',['../classcv_1_1videostab_1_1_motion_estimator_l1.html',1,'cv::videostab']]],
  ['motionestimatorransacl2',['MotionEstimatorRansacL2',['../classcv_1_1videostab_1_1_motion_estimator_ransac_l2.html',1,'cv::videostab']]],
  ['motionfilterbase',['MotionFilterBase',['../classcv_1_1videostab_1_1_motion_filter_base.html',1,'cv::videostab']]],
  ['motioninpainter',['MotionInpainter',['../classcv_1_1videostab_1_1_motion_inpainter.html',1,'cv::videostab']]],
  ['motionstabilizationpipeline',['MotionStabilizationPipeline',['../classcv_1_1videostab_1_1_motion_stabilization_pipeline.html',1,'cv::videostab']]],
  ['mser',['MSER',['../classcv_1_1_m_s_e_r.html',1,'cv']]],
  ['multibandblender',['MultiBandBlender',['../classcv_1_1detail_1_1_multi_band_blender.html',1,'cv::detail']]],
  ['mutex',['Mutex',['../classcv_1_1_mutex.html',1,'cv']]],
  ['mvnlayer',['MVNLayer',['../classcv_1_1dnn_1_1_m_v_n_layer.html',1,'cv::dnn']]]
];
